[workspace]
resolver = "2"
members = [
    "node",
    "contracts/aethel_token",
    "contracts/aethel_core",
]

[workspace.dependencies]
# Common
eyre = "0.6.8"
tokio = { version = "1", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
config = "0.13"
hex = "0.4"
tracing = "0.1"
thiserror = "1.0"

# Stylus Contracts
stylus-sdk = { version = "0.6.0", features = ["export-abi"] }
alloy-primitives = "0.7.2"
alloy-sol-types = { version = "0.7.2", features = ["json"] }

# Node Application
clap = { version = "4.0", features = ["derive"] }
ethers = "2.0.14"
sha3 = "0.10.8"
shellexpand = "3.1.0"
tracing-subscriber = "0.3.18"
